### ISSUE TITLE
Assets do not download, they now require HTTPS

### ISSUE THREAD

**Issue by joshuafhiggins** [DxxxxY/1.8.9ForgeTemplate#6]
When running 'setupDecompWorkspace' or 'runClient', errors occur when downloading assets. Following the links that fail show that the download servers require the use of HTTPS.

**Comment by dxxxxy** [comment]
> When running 'setupDecompWorkspace' or 'runClient', errors occur when downloading assets. Following the links that fail show that the download servers require the use of HTTPS.

You are right. Fortunately, only sounds and languages other than English do not download, which still allows Minecraft to run without much problems. Unfortunately, I am not the developer of the ForgeGradle plugin, so it is unlikely that it will be fixed in this template. This template purposely runs on older infrastructure to minimize the bloat and performance tanks of the newer models. If this issue bothers you, there are many other templates out there using the cutting-edge infrastructure.

Also, avoid running `runClient` from the Gradle tasks menu. Create a run configuration instead.
